#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 1
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 17

enum ts_symbol_identifiers {
  aux_sym_start_token1 = 1,
  aux_sym_start_token2 = 2,
  aux_sym_common_sep_token1 = 3,
  aux_sym_sep_token1 = 4,
  aux_sym__end_no_eol_token1 = 5,
  sym__char = 6,
  sym__eol = 7,
  sym_source_file = 8,
  aux_sym__body = 9,
  sym__conflict_no_end = 10,
  sym_conflict = 11,
  sym__conflict_no_eol = 12,
  sym_start = 13,
  sym_common_sep = 14,
  sym_sep = 15,
  sym_end = 16,
  sym__end_no_eol = 17,
  sym_comment = 18,
  aux_sym__comment_no_eol = 19,
  alias_sym_hunk = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_start_token1] = "start_token1",
  [aux_sym_start_token2] = "label",
  [aux_sym_common_sep_token1] = "common_sep_token1",
  [aux_sym_sep_token1] = "sep_token1",
  [aux_sym__end_no_eol_token1] = "_end_no_eol_token1",
  [sym__char] = "_char",
  [sym__eol] = "_eol",
  [sym_source_file] = "source_file",
  [aux_sym__body] = "_body",
  [sym__conflict_no_end] = "_conflict_no_end",
  [sym_conflict] = "conflict",
  [sym__conflict_no_eol] = "conflict",
  [sym_start] = "start",
  [sym_common_sep] = "common_sep",
  [sym_sep] = "sep",
  [sym_end] = "end",
  [sym__end_no_eol] = "_end_no_eol",
  [sym_comment] = "comment",
  [aux_sym__comment_no_eol] = "_comment_no_eol",
  [alias_sym_hunk] = "hunk",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_start_token1] = aux_sym_start_token1,
  [aux_sym_start_token2] = aux_sym_start_token2,
  [aux_sym_common_sep_token1] = aux_sym_common_sep_token1,
  [aux_sym_sep_token1] = aux_sym_sep_token1,
  [aux_sym__end_no_eol_token1] = aux_sym__end_no_eol_token1,
  [sym__char] = sym__char,
  [sym__eol] = sym__eol,
  [sym_source_file] = sym_source_file,
  [aux_sym__body] = aux_sym__body,
  [sym__conflict_no_end] = sym__conflict_no_end,
  [sym_conflict] = sym_conflict,
  [sym__conflict_no_eol] = sym_conflict,
  [sym_start] = sym_start,
  [sym_common_sep] = sym_common_sep,
  [sym_sep] = sym_sep,
  [sym_end] = sym_end,
  [sym__end_no_eol] = sym__end_no_eol,
  [sym_comment] = sym_comment,
  [aux_sym__comment_no_eol] = aux_sym__comment_no_eol,
  [alias_sym_hunk] = alias_sym_hunk,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_start_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_common_sep_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sep_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__end_no_eol_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__body] = {
    .visible = false,
    .named = false,
  },
  [sym__conflict_no_end] = {
    .visible = false,
    .named = true,
  },
  [sym_conflict] = {
    .visible = true,
    .named = true,
  },
  [sym__conflict_no_eol] = {
    .visible = true,
    .named = true,
  },
  [sym_start] = {
    .visible = true,
    .named = true,
  },
  [sym_common_sep] = {
    .visible = true,
    .named = true,
  },
  [sym_sep] = {
    .visible = true,
    .named = true,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [sym__end_no_eol] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__comment_no_eol] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_hunk] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_common = 1,
  field_label = 2,
  field_ours = 3,
  field_theirs = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_common] = "common",
  [field_label] = "label",
  [field_ours] = "ours",
  [field_theirs] = "theirs",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 3},
  [3] = {.index = 3, .length = 3},
  [5] = {.index = 6, .length = 4},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 1},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
  [15] = {.index = 22, .length = 2},
  [16] = {.index = 24, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_common, 0, .inherited = true},
    {field_ours, 0, .inherited = true},
    {field_theirs, 0, .inherited = true},
  [3] =
    {field_common, 1, .inherited = true},
    {field_ours, 1, .inherited = true},
    {field_theirs, 1, .inherited = true},
  [6] =
    {field_common, 0, .inherited = true},
    {field_label, 1, .inherited = true},
    {field_ours, 0, .inherited = true},
    {field_theirs, 0, .inherited = true},
  [10] =
    {field_label, 1},
  [11] =
    {field_label, 0, .inherited = true},
  [12] =
    {field_ours, 1},
  [13] =
    {field_theirs, 2},
  [14] =
    {field_ours, 1},
    {field_theirs, 3},
  [16] =
    {field_common, 2},
  [17] =
    {field_theirs, 3},
  [18] =
    {field_common, 3},
    {field_ours, 1},
  [20] =
    {field_ours, 1},
    {field_theirs, 4},
  [22] =
    {field_common, 2},
    {field_theirs, 4},
  [24] =
    {field_common, 3},
    {field_ours, 1},
    {field_theirs, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_comment,
  },
  [4] = {
    [1] = sym_comment,
  },
  [5] = {
    [1] = sym_end,
  },
  [8] = {
    [1] = alias_sym_hunk,
  },
  [9] = {
    [2] = alias_sym_hunk,
  },
  [10] = {
    [1] = alias_sym_hunk,
    [3] = alias_sym_hunk,
  },
  [11] = {
    [2] = alias_sym_hunk,
  },
  [12] = {
    [3] = alias_sym_hunk,
  },
  [13] = {
    [1] = alias_sym_hunk,
    [3] = alias_sym_hunk,
  },
  [14] = {
    [1] = alias_sym_hunk,
    [4] = alias_sym_hunk,
  },
  [15] = {
    [2] = alias_sym_hunk,
    [4] = alias_sym_hunk,
  },
  [16] = {
    [1] = alias_sym_hunk,
    [3] = alias_sym_hunk,
    [5] = alias_sym_hunk,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__body, 2,
    aux_sym__body,
    alias_sym_hunk,
  sym__end_no_eol, 2,
    sym__end_no_eol,
    sym_end,
  aux_sym__comment_no_eol, 2,
    aux_sym__comment_no_eol,
    sym_comment,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 9,
  [24] = 9,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 27,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 28,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 29,
  [41] = 27,
  [42] = 30,
  [43] = 43,
  [44] = 28,
  [45] = 27,
  [46] = 29,
  [47] = 30,
  [48] = 31,
  [49] = 28,
  [50] = 31,
  [51] = 29,
  [52] = 30,
  [53] = 31,
  [54] = 54,
  [55] = 43,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 54,
  [60] = 56,
  [61] = 54,
  [62] = 54,
  [63] = 56,
  [64] = 64,
  [65] = 56,
  [66] = 57,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 58,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 75,
  [81] = 75,
  [82] = 75,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '|') ADVANCE(37);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '|') ADVANCE(37);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '<') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '<') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == '|') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == '|') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == '|') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == '|') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == '|') ADVANCE(22);
      END_STATE();
    case 24:
      if (eof) ADVANCE(27);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 25:
      if (eof) ADVANCE(27);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_start_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_start_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_common_sep_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_sep_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__end_no_eol_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '<') ADVANCE(8);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '>') ADVANCE(18);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '|') ADVANCE(23);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__eol);
      if (lookahead == '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 25},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 24},
  [41] = {.lex_state = 24},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 25},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 24},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 25},
  [56] = {.lex_state = 25},
  [57] = {.lex_state = 26},
  [58] = {.lex_state = 25},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 25},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 25},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 25},
  [66] = {.lex_state = 26},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 26},
  [70] = {.lex_state = 26},
  [71] = {.lex_state = 25},
  [72] = {.lex_state = 26},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_start_token1] = ACTIONS(1),
    [aux_sym_common_sep_token1] = ACTIONS(1),
    [aux_sym_sep_token1] = ACTIONS(1),
    [aux_sym__end_no_eol_token1] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(77),
    [aux_sym__body] = STATE(6),
    [sym__conflict_no_end] = STATE(64),
    [sym_conflict] = STATE(41),
    [sym__conflict_no_eol] = STATE(76),
    [sym_start] = STATE(2),
    [sym_comment] = STATE(41),
    [aux_sym__comment_no_eol] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_start_token1] = ACTIONS(5),
    [sym__char] = ACTIONS(7),
    [sym__eol] = ACTIONS(9),
  },
  [2] = {
    [aux_sym__body] = STATE(3),
    [sym__conflict_no_end] = STATE(62),
    [sym_conflict] = STATE(27),
    [sym_start] = STATE(2),
    [sym_common_sep] = STATE(4),
    [sym_sep] = STATE(10),
    [sym_comment] = STATE(27),
    [aux_sym__comment_no_eol] = STATE(56),
    [aux_sym_start_token1] = ACTIONS(5),
    [aux_sym_common_sep_token1] = ACTIONS(11),
    [aux_sym_sep_token1] = ACTIONS(13),
    [sym__char] = ACTIONS(15),
    [sym__eol] = ACTIONS(17),
  },
  [3] = {
    [aux_sym__body] = STATE(9),
    [sym__conflict_no_end] = STATE(62),
    [sym_conflict] = STATE(27),
    [sym_start] = STATE(2),
    [sym_common_sep] = STATE(7),
    [sym_sep] = STATE(11),
    [sym_comment] = STATE(27),
    [aux_sym__comment_no_eol] = STATE(56),
    [aux_sym_start_token1] = ACTIONS(5),
    [aux_sym_common_sep_token1] = ACTIONS(11),
    [aux_sym_sep_token1] = ACTIONS(13),
    [sym__char] = ACTIONS(15),
    [sym__eol] = ACTIONS(17),
  },
  [4] = {
    [aux_sym__body] = STATE(5),
    [sym__conflict_no_end] = STATE(61),
    [sym_conflict] = STATE(45),
    [sym_start] = STATE(2),
    [sym_sep] = STATE(12),
    [sym_comment] = STATE(45),
    [aux_sym__comment_no_eol] = STATE(60),
    [aux_sym_start_token1] = ACTIONS(5),
    [aux_sym_sep_token1] = ACTIONS(13),
    [sym__char] = ACTIONS(15),
    [sym__eol] = ACTIONS(19),
  },
  [5] = {
    [aux_sym__body] = STATE(23),
    [sym__conflict_no_end] = STATE(61),
    [sym_conflict] = STATE(45),
    [sym_start] = STATE(2),
    [sym_sep] = STATE(17),
    [sym_comment] = STATE(45),
    [aux_sym__comment_no_eol] = STATE(60),
    [aux_sym_start_token1] = ACTIONS(5),
    [aux_sym_sep_token1] = ACTIONS(13),
    [sym__char] = ACTIONS(15),
    [sym__eol] = ACTIONS(19),
  },
  [6] = {
    [aux_sym__body] = STATE(13),
    [sym__conflict_no_end] = STATE(64),
    [sym_conflict] = STATE(41),
    [sym__conflict_no_eol] = STATE(74),
    [sym_start] = STATE(2),
    [sym_comment] = STATE(41),
    [aux_sym__comment_no_eol] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym_start_token1] = ACTIONS(5),
    [sym__char] = ACTIONS(7),
    [sym__eol] = ACTIONS(9),
  },
  [7] = {
    [aux_sym__body] = STATE(8),
    [sym__conflict_no_end] = STATE(61),
    [sym_conflict] = STATE(45),
    [sym_start] = STATE(2),
    [sym_sep] = STATE(15),
    [sym_comment] = STATE(45),
    [aux_sym__comment_no_eol] = STATE(60),
    [aux_sym_start_token1] = ACTIONS(5),
    [aux_sym_sep_token1] = ACTIONS(13),
    [sym__char] = ACTIONS(15),
    [sym__eol] = ACTIONS(19),
  },
  [8] = {
    [aux_sym__body] = STATE(23),
    [sym__conflict_no_end] = STATE(61),
    [sym_conflict] = STATE(45),
    [sym_start] = STATE(2),
    [sym_sep] = STATE(18),
    [sym_comment] = STATE(45),
    [aux_sym__comment_no_eol] = STATE(60),
    [aux_sym_start_token1] = ACTIONS(5),
    [aux_sym_sep_token1] = ACTIONS(13),
    [sym__char] = ACTIONS(15),
    [sym__eol] = ACTIONS(19),
  },
  [9] = {
    [aux_sym__body] = STATE(9),
    [sym__conflict_no_end] = STATE(62),
    [sym_conflict] = STATE(27),
    [sym_start] = STATE(2),
    [sym_comment] = STATE(27),
    [aux_sym__comment_no_eol] = STATE(56),
    [aux_sym_start_token1] = ACTIONS(23),
    [aux_sym_common_sep_token1] = ACTIONS(26),
    [aux_sym_sep_token1] = ACTIONS(26),
    [sym__char] = ACTIONS(28),
    [sym__eol] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(34), 1,
      aux_sym__end_no_eol_token1,
    ACTIONS(36), 1,
      sym__eol,
    STATE(2), 1,
      sym_start,
    STATE(14), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [29] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(38), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(16), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [58] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(40), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(22), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [87] = 9,
    ACTIONS(23), 1,
      aux_sym_start_token1,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      sym__char,
    ACTIONS(42), 1,
      sym__eol,
    STATE(2), 1,
      sym_start,
    STATE(13), 1,
      aux_sym__body,
    STATE(54), 1,
      sym__conflict_no_end,
    STATE(63), 1,
      aux_sym__comment_no_eol,
    STATE(41), 2,
      sym_conflict,
      sym_comment,
  [116] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(45), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [145] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(47), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(19), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [174] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(49), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [203] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(51), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(20), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [232] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(53), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(21), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [261] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(55), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [290] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(57), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [319] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(59), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [348] = 9,
    ACTIONS(5), 1,
      aux_sym_start_token1,
    ACTIONS(15), 1,
      sym__char,
    ACTIONS(36), 1,
      sym__eol,
    ACTIONS(61), 1,
      aux_sym__end_no_eol_token1,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [377] = 9,
    ACTIONS(23), 1,
      aux_sym_start_token1,
    ACTIONS(26), 1,
      aux_sym_sep_token1,
    ACTIONS(28), 1,
      sym__char,
    ACTIONS(63), 1,
      sym__eol,
    STATE(2), 1,
      sym_start,
    STATE(23), 1,
      aux_sym__body,
    STATE(60), 1,
      aux_sym__comment_no_eol,
    STATE(61), 1,
      sym__conflict_no_end,
    STATE(45), 2,
      sym_conflict,
      sym_comment,
  [406] = 9,
    ACTIONS(23), 1,
      aux_sym_start_token1,
    ACTIONS(26), 1,
      aux_sym__end_no_eol_token1,
    ACTIONS(28), 1,
      sym__char,
    ACTIONS(66), 1,
      sym__eol,
    STATE(2), 1,
      sym_start,
    STATE(24), 1,
      aux_sym__body,
    STATE(59), 1,
      sym__conflict_no_end,
    STATE(65), 1,
      aux_sym__comment_no_eol,
    STATE(32), 2,
      sym_conflict,
      sym_comment,
  [435] = 2,
    ACTIONS(71), 1,
      sym__char,
    ACTIONS(69), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [445] = 2,
    ACTIONS(75), 1,
      sym__char,
    ACTIONS(73), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [455] = 2,
    ACTIONS(79), 1,
      sym__char,
    ACTIONS(77), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [465] = 2,
    ACTIONS(83), 1,
      sym__char,
    ACTIONS(81), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [475] = 2,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(85), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [485] = 2,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [495] = 2,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 4,
      aux_sym_start_token1,
      aux_sym_common_sep_token1,
      aux_sym_sep_token1,
      sym__eol,
  [505] = 2,
    ACTIONS(79), 1,
      sym__char,
    ACTIONS(77), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [514] = 2,
    ACTIONS(99), 1,
      sym__char,
    ACTIONS(97), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [523] = 2,
    ACTIONS(103), 1,
      sym__char,
    ACTIONS(101), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [532] = 4,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym__char,
    ACTIONS(109), 1,
      sym__eol,
    STATE(43), 1,
      aux_sym__comment_no_eol,
  [545] = 2,
    ACTIONS(83), 1,
      sym__char,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      aux_sym_start_token1,
      sym__eol,
  [554] = 2,
    ACTIONS(113), 1,
      sym__char,
    ACTIONS(111), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [563] = 2,
    ACTIONS(117), 1,
      sym__char,
    ACTIONS(115), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [572] = 4,
    ACTIONS(107), 1,
      sym__char,
    ACTIONS(109), 1,
      sym__eol,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    STATE(43), 1,
      aux_sym__comment_no_eol,
  [585] = 2,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      aux_sym_start_token1,
      sym__eol,
  [594] = 2,
    ACTIONS(79), 1,
      sym__char,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      aux_sym_start_token1,
      sym__eol,
  [603] = 2,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      aux_sym_start_token1,
      sym__eol,
  [612] = 3,
    ACTIONS(123), 1,
      sym__char,
    STATE(43), 1,
      aux_sym__comment_no_eol,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym__eol,
  [623] = 2,
    ACTIONS(83), 1,
      sym__char,
    ACTIONS(81), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [632] = 2,
    ACTIONS(79), 1,
      sym__char,
    ACTIONS(77), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [641] = 2,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(85), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [650] = 2,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [659] = 2,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 3,
      aux_sym_start_token1,
      aux_sym_sep_token1,
      sym__eol,
  [668] = 2,
    ACTIONS(83), 1,
      sym__char,
    ACTIONS(81), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [677] = 2,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      aux_sym_start_token1,
      sym__eol,
  [686] = 2,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(85), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [695] = 2,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [704] = 2,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 3,
      aux_sym_start_token1,
      aux_sym__end_no_eol_token1,
      sym__eol,
  [713] = 3,
    ACTIONS(126), 1,
      aux_sym__end_no_eol_token1,
    STATE(40), 1,
      sym_end,
    STATE(75), 1,
      sym__end_no_eol,
  [723] = 3,
    ACTIONS(121), 1,
      sym__eol,
    ACTIONS(128), 1,
      sym__char,
    STATE(55), 1,
      aux_sym__comment_no_eol,
  [733] = 3,
    ACTIONS(131), 1,
      sym__char,
    ACTIONS(133), 1,
      sym__eol,
    STATE(55), 1,
      aux_sym__comment_no_eol,
  [743] = 2,
    ACTIONS(137), 1,
      aux_sym_start_token2,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym__eol,
  [751] = 1,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      sym__char,
      sym__eol,
  [757] = 3,
    ACTIONS(126), 1,
      aux_sym__end_no_eol_token1,
    STATE(51), 1,
      sym_end,
    STATE(82), 1,
      sym__end_no_eol,
  [767] = 3,
    ACTIONS(131), 1,
      sym__char,
    ACTIONS(141), 1,
      sym__eol,
    STATE(55), 1,
      aux_sym__comment_no_eol,
  [777] = 3,
    ACTIONS(126), 1,
      aux_sym__end_no_eol_token1,
    STATE(46), 1,
      sym_end,
    STATE(80), 1,
      sym__end_no_eol,
  [787] = 3,
    ACTIONS(126), 1,
      aux_sym__end_no_eol_token1,
    STATE(29), 1,
      sym_end,
    STATE(81), 1,
      sym__end_no_eol,
  [797] = 3,
    ACTIONS(109), 1,
      sym__eol,
    ACTIONS(131), 1,
      sym__char,
    STATE(55), 1,
      aux_sym__comment_no_eol,
  [807] = 3,
    ACTIONS(143), 1,
      aux_sym__end_no_eol_token1,
    STATE(40), 1,
      sym_end,
    STATE(67), 1,
      sym__end_no_eol,
  [817] = 3,
    ACTIONS(131), 1,
      sym__char,
    ACTIONS(145), 1,
      sym__eol,
    STATE(55), 1,
      aux_sym__comment_no_eol,
  [827] = 2,
    ACTIONS(135), 1,
      sym__eol,
    ACTIONS(137), 1,
      aux_sym_start_token2,
  [834] = 2,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 1,
      sym__eol,
  [841] = 1,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      sym__eol,
  [846] = 2,
    ACTIONS(153), 1,
      aux_sym_start_token2,
    ACTIONS(155), 1,
      sym__eol,
  [853] = 2,
    ACTIONS(157), 1,
      aux_sym_start_token2,
    ACTIONS(159), 1,
      sym__eol,
  [860] = 1,
    ACTIONS(139), 2,
      sym__char,
      sym__eol,
  [865] = 2,
    ACTIONS(161), 1,
      aux_sym_start_token2,
    ACTIONS(163), 1,
      sym__eol,
  [872] = 1,
    ACTIONS(165), 1,
      sym__eol,
  [876] = 1,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
  [880] = 1,
    ACTIONS(149), 1,
      sym__eol,
  [884] = 1,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
  [888] = 1,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
  [892] = 1,
    ACTIONS(173), 1,
      sym__eol,
  [896] = 1,
    ACTIONS(175), 1,
      sym__eol,
  [900] = 1,
    ACTIONS(177), 1,
      sym__eol,
  [904] = 1,
    ACTIONS(179), 1,
      sym__eol,
  [908] = 1,
    ACTIONS(181), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 29,
  [SMALL_STATE(12)] = 58,
  [SMALL_STATE(13)] = 87,
  [SMALL_STATE(14)] = 116,
  [SMALL_STATE(15)] = 145,
  [SMALL_STATE(16)] = 174,
  [SMALL_STATE(17)] = 203,
  [SMALL_STATE(18)] = 232,
  [SMALL_STATE(19)] = 261,
  [SMALL_STATE(20)] = 290,
  [SMALL_STATE(21)] = 319,
  [SMALL_STATE(22)] = 348,
  [SMALL_STATE(23)] = 377,
  [SMALL_STATE(24)] = 406,
  [SMALL_STATE(25)] = 435,
  [SMALL_STATE(26)] = 445,
  [SMALL_STATE(27)] = 455,
  [SMALL_STATE(28)] = 465,
  [SMALL_STATE(29)] = 475,
  [SMALL_STATE(30)] = 485,
  [SMALL_STATE(31)] = 495,
  [SMALL_STATE(32)] = 505,
  [SMALL_STATE(33)] = 514,
  [SMALL_STATE(34)] = 523,
  [SMALL_STATE(35)] = 532,
  [SMALL_STATE(36)] = 545,
  [SMALL_STATE(37)] = 554,
  [SMALL_STATE(38)] = 563,
  [SMALL_STATE(39)] = 572,
  [SMALL_STATE(40)] = 585,
  [SMALL_STATE(41)] = 594,
  [SMALL_STATE(42)] = 603,
  [SMALL_STATE(43)] = 612,
  [SMALL_STATE(44)] = 623,
  [SMALL_STATE(45)] = 632,
  [SMALL_STATE(46)] = 641,
  [SMALL_STATE(47)] = 650,
  [SMALL_STATE(48)] = 659,
  [SMALL_STATE(49)] = 668,
  [SMALL_STATE(50)] = 677,
  [SMALL_STATE(51)] = 686,
  [SMALL_STATE(52)] = 695,
  [SMALL_STATE(53)] = 704,
  [SMALL_STATE(54)] = 713,
  [SMALL_STATE(55)] = 723,
  [SMALL_STATE(56)] = 733,
  [SMALL_STATE(57)] = 743,
  [SMALL_STATE(58)] = 751,
  [SMALL_STATE(59)] = 757,
  [SMALL_STATE(60)] = 767,
  [SMALL_STATE(61)] = 777,
  [SMALL_STATE(62)] = 787,
  [SMALL_STATE(63)] = 797,
  [SMALL_STATE(64)] = 807,
  [SMALL_STATE(65)] = 817,
  [SMALL_STATE(66)] = 827,
  [SMALL_STATE(67)] = 834,
  [SMALL_STATE(68)] = 841,
  [SMALL_STATE(69)] = 846,
  [SMALL_STATE(70)] = 853,
  [SMALL_STATE(71)] = 860,
  [SMALL_STATE(72)] = 865,
  [SMALL_STATE(73)] = 872,
  [SMALL_STATE(74)] = 876,
  [SMALL_STATE(75)] = 880,
  [SMALL_STATE(76)] = 884,
  [SMALL_STATE(77)] = 888,
  [SMALL_STATE(78)] = 892,
  [SMALL_STATE(79)] = 896,
  [SMALL_STATE(80)] = 900,
  [SMALL_STATE(81)] = 904,
  [SMALL_STATE(82)] = 908,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2, 0, 0), SHIFT_REPEAT(72),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__body, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__body, 2, 0, 0), SHIFT_REPEAT(71),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2, 0, 0), SHIFT_REPEAT(28),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 3, 0, 8),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 3, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2, 0, 0), SHIFT_REPEAT(36),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 3, 0, 9),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 4, 0, 8),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 4, 0, 10),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 4, 0, 11),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 5, 0, 13),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 5, 0, 14),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 5, 0, 15),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 6, 0, 16),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_end, 4, 0, 12),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2, 0, 0), SHIFT_REPEAT(44),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body, 2, 0, 0), SHIFT_REPEAT(49),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start, 3, 0, 6),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start, 3, 0, 6),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__body, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__body, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__body, 1, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__body, 1, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conflict, 2, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conflict, 2, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end, 2, 0, 7),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end, 2, 0, 7),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_common_sep, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_common_sep, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sep, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sep, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_common_sep, 3, 0, 6),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_common_sep, 3, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sep, 3, 0, 6),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sep, 3, 0, 6),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_no_eol, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_no_eol, 2, 0, 0), SHIFT_REPEAT(58),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_no_eol, 2, 0, 0), SHIFT_REPEAT(71),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_no_eol, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_no_eol, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__conflict_no_eol, 2, 0, 5),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_no_eol, 2, 0, 6),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 2),
  [171] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_git_merge_conflict(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
